### ISSUE TITLE
Frontend requires the core to point to api.hostname

### ISSUE THREAD

**Issue by JaysonDeMarchi** [deso-protocol/frontend#33]
The way the core url variable is configured it assumes it will always be `api.{hostname}`.

https://github.com/bitclout/frontend/blob/47b63826780a1ef9d2291f36605449cc6308d7e0/src/app/global-vars.service.ts#L608

This limits environment flexibility, and tightly couples the core with frontend. A backend service in a separate container should not be dependent on the frontend's configuration.

Some affected use cases:
- Hosted test apps: These services generally don't allow custom urls and can be discouraging to new developers. This bug creates a larger barrier of entry for a new dev to spin up a node.
- Sharing cores: If I have two sites (bitclout.com and bitclout.co.uk) then I also need to setup separate two core clusters? This seems redundant, and increases the cost to spin up additional nodes.

My suggestion is to move the core url to either the angular.json file or we use a `.env` file and possible import the dotenv package to this project. Not sure if angular inherently adds it to node modules.

**Comment by maebeam** [comment]
Please feel free to move this into `enviroment.ts`

**Comment by JaysonDeMarchi** [comment]
Ah that sounds like a great place for this.

**Comment by jagathks** [comment]
i think we can close this: commit: https://github.com/deso-protocol/frontend/commit/5bce5a78159162a78c9bb0bd800f68a964c5f081
