### ISSUE TITLE
Node Fees Issue - NFT Bid Notification Shows

### ISSUE THREAD

**Issue by tijno** [deso-protocol/frontend#481]
Not sure if this is intential - it probably is not.

I bid from my kennybeats account on this NFT https://tijn.club/nft/7db7f7db47056c5288512aee09ec690d7db8cd40a996b33ce303184e10fe4a81?tab=posts

That NFT is NOT owned by me (tijn account).

But it still showed in notifications for tijn and machijno accounts - which are the fee beneficiaries. 

I suspect this is probably a bug in notifications not filtering out this fee payment transaction and treating it as a bid on my NFT.

![20211012-ZOeuoF6q](https://user-images.githubusercontent.com/69529928/136942730-7da3307a-865f-49a5-8d76-b3c98cc3470a.png)

**Comment by kennybeats** [comment]
you should be sorry

**Comment by kennybeats** [comment]
im kenny beats

**Comment by kennybeats** [comment]
you can never be me

**Comment by maebeam** [comment]
Fixed in https://github.com/deso-protocol/backend/pull/207

**Comment by kennybeats** [comment]
@maebeam im kenny beats. fuck you
