### ISSUE TITLE
Frontend Character Limit in Posts Not Enforced By Validators

### ISSUE THREAD

**Issue by LukeWalsh** [deso-protocol/frontend#49]
It's possible to post with more than 280 characters, is this intentional? https://bitclout.com/posts/58f568d98ef9db3a5e3cbb619fd0f54e38bc50059e6669e1c6ab73cc72582326?feedTab=Following

Overall I'm a pretty big fan of dropping the character limit entirely, never really liked that about Twitter myself. At the same time, if things get REALLY long people might be curious to know what's being paid for that space.

**Comment by maebeam** [comment]
This is a rather large product decision for our frontend app. In the short term, if someone wants to implement "click to expand" on posts that bypass the character limit, please go ahead.
